- src: geerlingguy.ntp
  version: 1.5.2
- src: geerlingguy.redis
  version: 1.5.1
- src: geerlingguy.php
  version: 3.4.5
- src: VerosK.acme-sh
  version: 1.1.0
- src: VerosK.nginx
  version: 1.1.2
- name: VerosK.fake-certs
  src: https://github.com/VerosK/ansible-fake-certs
- name: VerosK.postgresql
  src: https://github.com/VerosK/ansible-role-postgresql
- name: VerosK.icinga2
  src: https://github.com/VerosK/ansible-icinga2-role
- name: VerosK.icingaclassic
  src: https://github.com/VerosK/ansible-icingaclassic-cgi
- name: VerosK.icingaweb2-php-fpm
  src: https://github.com/VerosK/ansible-icingaweb2-php-fpm
